
server {
    listen 80;
   
    server_name api.loresuelvo.com.ar api-test.loresuelvo.com.ar;
    
    location / { 
        proxy_pass http://api:8080; 
    }
}

# server {
#     listen 80;

#     server_name loresuelvo.com.ar www.loresuelvo.com.ar test.loresuelvo.com.ar;
    
#     location / { 
#         proxy_pass http://loresuelvo:3000; 
#     }
# }

# server {
#     listen 80;
  
#     server_name gestion.loresuelvo.com.ar gestion-test.loresuelvo.com.ar;
    
#     location / { 
#         proxy_pass http://gestion:3000; 
#     }
# }