# Proxy listening on port 80 of the dropplet
server {
    listen 80;
    server_name api.tu-dominio.com;
    
    # Deriva al contenedor 'api' en su puerto interno 8080
    location / { proxy_pass http://api:8080; }
}

server {
    listen 80;
    server_name front1.tu-dominio.com;
    
    # Deriva al contenedor 'frontend-uno' (definido en el repo del front 1)
    location / { proxy_pass http://frontend-uno:3000; }
}

server {
    listen 80;
    server_name front2.tu-dominio.com;
    
    # Deriva al contenedor 'frontend-dos'
    location / { proxy_pass http://frontend-dos:3000; }
}
