package file

import "errors"

var (
	ErrFileIDRequired              = errors.New("File id is required")
	ErrFileKeyRequired             = errors.New("File key is required")
	ErrFileBucketRequired          = errors.New("File bucket is required")
	ErrFileTimestampRequired       = errors.New("File timestamp is required")
	ErrFileStatusRequired          = errors.New("File status is required")
	ErrFileMetadataRequired        = errors.New("File metadata is required")
	ErrOriginalNameRequired        = errors.New("Original name is required")
	ErrMimeTypeRequired            = errors.New("Mime type is required")
	ErrSizeRequired                = errors.New("File size is required")
	ErrVisibilityRequired          = errors.New("File visibility is required")
	ErrPurposeRequired             = errors.New("File purpose is required")
	ErrUploaderRequired            = errors.New("File uploader is required")
	ErrFileNotAvailable            = errors.New("File could not be uploaded")
	ErrUnsupportedPurpose          = errors.New("File purpose is not supported")
	ErrUnsupportedProfilePhoto     = errors.New("Profile photo could not be uploaded")
	ErrProfilePhotoRequired        = errors.New("Profile photo is required")
	ErrProfilePhotoNotAvailable    = errors.New("Profile photo could not be uploaded")
	ErrMessageImageNotAvailable    = errors.New("Message image is not available")
	ErrUnsupportedMessageAudio     = errors.New("Message audio could not be uploaded")
	ErrMessageAudioNotAvailable    = errors.New("Message audio is not available")
	ErrAudioDurationRequired       = errors.New("Audio duration is required")
	ErrAudioCodecRequired          = errors.New("Audio codec is required")
	ErrUnsupportedMessageVideo     = errors.New("Message video could not be uploaded")
	ErrMessageVideoNotAvailable    = errors.New("Message video is not available")
	ErrVideoDurationRequired       = errors.New("Video duration is required")
	ErrVideoCodecRequired          = errors.New("Video codec is required")
	ErrVideoDimensionsRequired     = errors.New("Video dimensions are required")
	ErrJobRequestImageNotAvailable = errors.New("Job request image is not available")
)
