name: Release & Deploy

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login a GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build y Push de la imagen
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/api:${{ github.ref_name }} .
          docker push --all-tags ghcr.io/${{ github.repository_owner }}/api

  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH a Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_STAGING_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_STAGING_SSH_KEY }}
          script: |
            set -e
            cd /app/api
            git fetch --tags --force
            git checkout ${{ github.ref_name }}
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_TEST }}" > .env
            export IMAGE_TAG=${{ github.ref_name }}
            export GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH a Producción
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_PROD_IP }} 
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PROD_SSH_KEY }}
          script: |
            set -e
            cd ~/loresuelvo-api
            git fetch --tags --force
            git checkout ${{ github.ref_name }}
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" > .env
            export IMAGE_TAG=${{ github.ref_name }}
            export GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f